#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SimpleSample.Droid.Resource", IsApplication=true)]

namespace SimpleSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SimpleAuth.Resource.String.ApplicationName = global::SimpleSample.Droid.Resource.String.ApplicationName;
			global::SimpleAuth.Resource.String.Hello = global::SimpleSample.Droid.Resource.String.Hello;
			global::ModernHttpClient.Resource.String.library_name = global::SimpleSample.Droid.Resource.String.library_name;
			global::SimpleTables.Resource.Animation.slide_in_left = global::SimpleSample.Droid.Resource.Animation.slide_in_left;
			global::SimpleTables.Resource.Animation.slide_in_right = global::SimpleSample.Droid.Resource.Animation.slide_in_right;
			global::SimpleTables.Resource.Animation.slide_out_left = global::SimpleSample.Droid.Resource.Animation.slide_out_left;
			global::SimpleTables.Resource.Animation.slide_out_right = global::SimpleSample.Droid.Resource.Animation.slide_out_right;
			global::SimpleTables.Resource.Drawable.dialog_disclosure = global::SimpleSample.Droid.Resource.Drawable.dialog_disclosure;
			global::SimpleTables.Resource.Drawable.dialog_expander_ic_minimized = global::SimpleSample.Droid.Resource.Drawable.dialog_expander_ic_minimized;
			global::SimpleTables.Resource.Id.LinearLayout01 = global::SimpleSample.Droid.Resource.Id.LinearLayout01;
			global::SimpleTables.Resource.Id.dialog_BoolField = global::SimpleSample.Droid.Resource.Id.dialog_BoolField;
			global::SimpleTables.Resource.Id.dialog_Button = global::SimpleSample.Droid.Resource.Id.dialog_Button;
			global::SimpleTables.Resource.Id.dialog_DisclosureField = global::SimpleSample.Droid.Resource.Id.dialog_DisclosureField;
			global::SimpleTables.Resource.Id.dialog_ImageLeft = global::SimpleSample.Droid.Resource.Id.dialog_ImageLeft;
			global::SimpleTables.Resource.Id.dialog_ImageRight = global::SimpleSample.Droid.Resource.Id.dialog_ImageRight;
			global::SimpleTables.Resource.Id.dialog_LabelField = global::SimpleSample.Droid.Resource.Id.dialog_LabelField;
			global::SimpleTables.Resource.Id.dialog_LabelSubtextField = global::SimpleSample.Droid.Resource.Id.dialog_LabelSubtextField;
			global::SimpleTables.Resource.Id.dialog_Panel = global::SimpleSample.Droid.Resource.Id.dialog_Panel;
			global::SimpleTables.Resource.Id.dialog_RadioButtonList = global::SimpleSample.Droid.Resource.Id.dialog_RadioButtonList;
			global::SimpleTables.Resource.Id.dialog_SliderField = global::SimpleSample.Droid.Resource.Id.dialog_SliderField;
			global::SimpleTables.Resource.Id.dialog_Spinner = global::SimpleSample.Droid.Resource.Id.dialog_Spinner;
			global::SimpleTables.Resource.Id.dialog_ValueField = global::SimpleSample.Droid.Resource.Id.dialog_ValueField;
			global::SimpleTables.Resource.Id.iFormFieldValue = global::SimpleSample.Droid.Resource.Id.iFormFieldValue;
			global::SimpleTables.Resource.Id.title = global::SimpleSample.Droid.Resource.Id.title;
			global::SimpleTables.Resource.Id.uinavigationLeftButtonLayout = global::SimpleSample.Droid.Resource.Id.uinavigationLeftButtonLayout;
			global::SimpleTables.Resource.Id.uinavigationRightButtonLayout = global::SimpleSample.Droid.Resource.Id.uinavigationRightButtonLayout;
			global::SimpleTables.Resource.Id.uinavigationcontent = global::SimpleSample.Droid.Resource.Id.uinavigationcontent;
			global::SimpleTables.Resource.Id.uinavigationleftbtn = global::SimpleSample.Droid.Resource.Id.uinavigationleftbtn;
			global::SimpleTables.Resource.Id.uinavigationrightbtn = global::SimpleSample.Droid.Resource.Id.uinavigationrightbtn;
			global::SimpleTables.Resource.Layout.anav = global::SimpleSample.Droid.Resource.Layout.anav;
			global::SimpleTables.Resource.Layout.dialog_achievements = global::SimpleSample.Droid.Resource.Layout.dialog_achievements;
			global::SimpleTables.Resource.Layout.dialog_boolfieldleft = global::SimpleSample.Droid.Resource.Layout.dialog_boolfieldleft;
			global::SimpleTables.Resource.Layout.dialog_boolfieldright = global::SimpleSample.Droid.Resource.Layout.dialog_boolfieldright;
			global::SimpleTables.Resource.Layout.dialog_boolfieldsubleft = global::SimpleSample.Droid.Resource.Layout.dialog_boolfieldsubleft;
			global::SimpleTables.Resource.Layout.dialog_boolfieldsubright = global::SimpleSample.Droid.Resource.Layout.dialog_boolfieldsubright;
			global::SimpleTables.Resource.Layout.dialog_button = global::SimpleSample.Droid.Resource.Layout.dialog_button;
			global::SimpleTables.Resource.Layout.dialog_datefield = global::SimpleSample.Droid.Resource.Layout.dialog_datefield;
			global::SimpleTables.Resource.Layout.dialog_fieldsetlabel = global::SimpleSample.Droid.Resource.Layout.dialog_fieldsetlabel;
			global::SimpleTables.Resource.Layout.dialog_floatimage = global::SimpleSample.Droid.Resource.Layout.dialog_floatimage;
			global::SimpleTables.Resource.Layout.dialog_labelfieldbelow = global::SimpleSample.Droid.Resource.Layout.dialog_labelfieldbelow;
			global::SimpleTables.Resource.Layout.dialog_labelfieldright = global::SimpleSample.Droid.Resource.Layout.dialog_labelfieldright;
			global::SimpleTables.Resource.Layout.dialog_onofffieldright = global::SimpleSample.Droid.Resource.Layout.dialog_onofffieldright;
			global::SimpleTables.Resource.Layout.dialog_panel = global::SimpleSample.Droid.Resource.Layout.dialog_panel;
			global::SimpleTables.Resource.Layout.dialog_root = global::SimpleSample.Droid.Resource.Layout.dialog_root;
			global::SimpleTables.Resource.Layout.dialog_selectlist = global::SimpleSample.Droid.Resource.Layout.dialog_selectlist;
			global::SimpleTables.Resource.Layout.dialog_selectlistfield = global::SimpleSample.Droid.Resource.Layout.dialog_selectlistfield;
			global::SimpleTables.Resource.Layout.dialog_textarea = global::SimpleSample.Droid.Resource.Layout.dialog_textarea;
			global::SimpleTables.Resource.Layout.dialog_textfieldbelow = global::SimpleSample.Droid.Resource.Layout.dialog_textfieldbelow;
			global::SimpleTables.Resource.Layout.dialog_textfieldright = global::SimpleSample.Droid.Resource.Layout.dialog_textfieldright;
			global::SimpleTables.Resource.String.library_name = global::SimpleSample.Droid.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int enter = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int exit = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int slide_in_left = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int slide_in_right = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int slide_out_left = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int slide_out_right = 2131034117;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout01 = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int dialog_BoolField = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int dialog_Button = 2131165194;
			
			// aapt resource value: 0x7f070010
			public const int dialog_DisclosureField = 2131165200;
			
			// aapt resource value: 0x7f07000c
			public const int dialog_ImageLeft = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int dialog_ImageRight = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int dialog_LabelField = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int dialog_LabelSubtextField = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int dialog_Panel = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int dialog_RadioButtonList = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int dialog_SliderField = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int dialog_Spinner = 2131165202;
			
			// aapt resource value: 0x7f07000b
			public const int dialog_ValueField = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int iFormFieldValue = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int title = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int uinavigationLeftButtonLayout = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int uinavigationRightButtonLayout = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int uinavigationcontent = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int uinavigationleftbtn = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int uinavigationrightbtn = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int anav = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialog_achievements = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dialog_boolfieldleft = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_boolfieldright = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dialog_boolfieldsubleft = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int dialog_boolfieldsubright = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int dialog_button = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int dialog_datefield = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int dialog_fieldsetlabel = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int dialog_floatimage = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int dialog_labelfieldbelow = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int dialog_labelfieldright = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int dialog_onofffieldright = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int dialog_panel = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int dialog_root = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int dialog_selectlist = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int dialog_selectlistfield = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int dialog_textarea = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int dialog_textfieldbelow = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int dialog_textfieldright = 2130968595;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060002
			public const int ApplicationName = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int hello = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
